GET http://localhost:4000/user
Accept: application/json

###
POST http://localhost:4000/user
Accept: application/json
Content-Type: application/json

{
  "name": "Felipe",
  "email": "ueahara3@gamil.com"
}